name: safeboxx
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  google_sign_in: ^4.4.4
  shared_preferences: ^0.5.3+4
  provider: ^2.0.1+1
  get_it:
  progress_hud: ^1.1.0
  #  fluttertoast: ^2.0.7
  flutter_svg: ^0.6.1+1
  file_picker: ^2.1.4
  image: ^2.1.4
  image_picker_for_web: ^0.1.0+2
  intro_views_flutter: ^2.8.2
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.3
  random_color: ^1.0.5
  camera: 0.7.0
  custom_radio_grouped_button: 1.0.0
  dio: ^3.0.10
  division: ^0.8.8
  flutter_spinkit: ^4.1.2+1
  mobx: ^1.1.1
  numeric_keyboard: ^1.0.0
  flutter_mobx: ^1.1.0

  cupertino_icons: ^1.0.0
  image_picker:
  firebase_auth:
  cloud_firestore:
  firebase_core:
  firebase_storage: ^5.0.1






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

#  cupertino_icons: ^1.0.0
  animator: ^1.0.0+3
  flutter_page_indicator: ^0.0.3
  gradient_text: ^1.0.2
  modal_progress_hud: ^0.1.3
  http: ^0.12.2
  path_provider: ^1.6.22
  font_awesome_flutter: ^8.10.0
  cached_network_image: ^2.3.3
  shimmer: ^1.1.2
  screen: ^0.0.5
  percent_indicator: ^2.1.8
  connectivity: ^2.0.0
  flutter_sparkline: ^0.1.0
  intl: ^0.16.1
  flutter_webview_plugin: ^0.3.11
  location: ^3.0.2
  admob_flutter: ^1.0.1
  credit_card: 0.1.6



  flutter_localizations:
    sdk: flutter



  firebase_analytics:



  # google_sign_in:
  # apple_sign_in:


  # upstate:

  flutter_platform_widgets:
  flutter_sheet_localization: ^1.0.0
  simple_gravatar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: ^1.0.0
  build_runner: ^1.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true

#  plugin:
#    platforms:
#      android:
#        package: com.safe.safeboxx
#        pluginClass:  FlutterPaystackPlugin
#      ios:
#        pluginClass:  FlutterPaystackPlugin

  # To add assets to your application, add an assets section, like this:
  assets:
    #    - assets/email.svg
    #    - assets/gmail.svg
    #    - assets/smartphone.svg
    - assets/splashBackground.jpg
    - assets/appIcon.png
    - assets/planet.png
    - assets/authImage.jpg
    - assets/selectAuth.jpg
    - assets/userImage.png
    - assets/clap.png
    - assets/sparkles.png
    - assets/barcode.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu-BoldItalic.ttf
        - asset: fonts/Ubuntu-Italic.ttf
        - asset: fonts/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu-LightItalic.ttf
        - asset: fonts/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu-MediumItalic.ttf
        - asset: fonts/Ubuntu-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages